'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class especialidad

    '''<summary>
    '''ddpaises control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddpaises As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddciudades1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddciudades1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddespecialidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddespecialidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBuscarXPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarXPais As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBuscarXCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarXCiudad As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBuscarXEspecialidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarXEspecialidad As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPaisOCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaisOCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgvResultados1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvResultados1 As Global.System.Web.UI.WebControls.GridView
End Class
